(self.AMP=self.AMP||[]).push({n:"amp-soundcloud",v:"2006112352001",f:(function(AMP,_){
var c="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function g(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],d=0;d<b.length;++d){var e=b[d];if(e&&e.Math==Math)return}(function(){throw Error("Cannot find global object");})()}g(this);"function"===typeof Symbol&&Symbol("x");var h;
if("function"==typeof Object.setPrototypeOf)h=Object.setPrototypeOf;else{var k;a:{var l={a:!0},m={};try{m.__proto__=l;k=m.a;break a}catch(a){}k=!1}h=k?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var p=h;var q=self.AMP_CONFIG||{},r=("string"==typeof q.cdnProxyRegex?new RegExp(q.cdnProxyRegex):q.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function t(a){if(self.document&&self.document.head&&(!self.location||!r.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}q.cdnUrl||t("runtime-host");q.geoApiUrl||t("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var u=self.__AMP_LOG;function v(a){return a||{}};v({c:!0,v:!0,a:!0,ad:!0,action:!0});/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function x(a){a=AMP.BaseElement.call(this,a)||this;a.h=null;return a}var y=AMP.BaseElement;x.prototype=c(y.prototype);x.prototype.constructor=x;if(p)p(x,y);else for(var z in y)if("prototype"!=z)if(Object.defineProperties){var A=Object.getOwnPropertyDescriptor(y,z);A&&Object.defineProperty(x,z,A)}else x[z]=y[z];x.j=y.prototype;
x.prototype.preconnectCallback=function(a){var b=this.win;b=b.__AMP_TOP||(b.__AMP_TOP=b);var d=b.__AMP_SERVICES;d||(d=b.__AMP_SERVICES={});b=d.preconnect;b.obj||(b.obj=new b.ctor(b.context),b.ctor=null,b.context=null,b.resolve&&b.resolve(b.obj));b.obj.url(this.getAmpDoc(),"https://api.soundcloud.com/",a)};x.prototype.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a||"fluid"==a||"intrinsic"==a};x.prototype.buildCallback=function(){this.element.classList.add("i-amphtml-media-component")};
x.prototype.layoutCallback=function(){var a=this.element.getAttribute("height"),b=this.element.getAttribute("data-color"),d=this.element.getAttribute("data-visual"),e="https://api.soundcloud.com/"+(this.element.hasAttribute("data-trackid")?"tracks":"playlists")+"/";var n=this.element.getAttribute("data-trackid")||this.element.getAttribute("data-playlistid");var B=this.element;if(!u.user)throw Error("failed to call initLogConstructor");n=u.user.assert(n,"data-trackid or data-playlistid is required for <amp-soundcloud> %s",
B,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0);var w=this.element.getAttribute("data-secret-token"),f=this.element.ownerDocument.createElement("iframe");f.setAttribute("frameborder","no");f.setAttribute("scrolling","no");e="https://w.soundcloud.com/player/?url="+encodeURIComponent(e+n);w&&(e+=encodeURIComponent("?secret_token="+w));"true"===d?e+="&visual=true":b&&(e+="&color="+encodeURIComponent(b));f.src=e;this.applyFillContent(f);f.height=a;this.element.appendChild(f);this.h=f;return this.loadPromise(f)};
x.prototype.pauseCallback=function(){this.h&&this.h.contentWindow&&this.h.contentWindow.postMessage(JSON.stringify(v({method:"pause"})),"https://w.soundcloud.com")};(function(a){a.registerElement("amp-soundcloud",x)})(self.AMP);
})});

//# sourceMappingURL=amp-soundcloud-0.1.js.map
